```{r Setup}
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
library(maps)
library(mapproj)
library(stringr)
library(openintro)
library(viridis)

# Set working directory to the location of this file
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

# Data Import & Cleaning

```{r Import data}
policy_df <- read_csv("data/state_policy_updates_11-15.csv", col_types = cols())
county_pop_df <- read_csv("data/county_pop.csv", col_types = cols())

county_cases_df <- read_csv("data/cumulative_cases_11-15.csv", col_types = cols())
county_cases_df <- county_cases_df %>% select(-c(UID:code3, Country_Region:Combined_Key))

county_deaths_df <- read_csv("data/cumulative_deaths_11-15.csv", col_types = cols())
county_deaths_df <- county_deaths_df %>% select(-c(UID:code3, Country_Region:Combined_Key))

mask_use_raw <- read_csv("data/mask-use-by-county.csv", col_types = cols())
mask_use_df <- mask_use_raw %>% mutate(COUNTYFP = as.double(COUNTYFP))
```

```{r Reorganize data into daily and/or per capita measurements}
reorganize_data <- function(data, cumulative=c(FALSE, TRUE), population_adjusted=c(FALSE, TRUE)) {
  # Add population data, state codes, and median age to the wide data
  new_df <- left_join(data, county_pop_df, by=c("FIPS" = "fips")) %>%
    filter(!is.na(county)) %>%
    select(FIPS, county, state_code, population, median_age, ends_with("/20"))
  
  # Create a copy for reference
  df_copy <- data.frame(new_df)


  if (cumulative) {
    if (population_adjusted) {
      # Adjust the cumulative values to be percent of population
      for (i in 6:(ncol(new_df))) {
          new_df[i] <- df_copy[i] / df_copy$population
      }
    } else {
      # Do nothing
    }
  } else {
    # Adjust the daily values to be percent of population
    if (population_adjusted) {
      for (i in 6:(ncol(new_df))) {
        if (i == 6) {
          new_df[i] <- df_copy[i] / df_copy$population
        } else {
          new_df[i] <- (df_copy[i] - df_copy[i-1]) / df_copy$population
        }
      }
    } else {
      # Adjust the values to be daily values
      for (i in 7:(ncol(new_df))) {
        new_df[i] <- df_copy[i] - df_copy[i-1]
      }
    }
  }
  
  # Convert data to a longer form
  new_df <- new_df %>%
  pivot_longer(cols = ends_with("/20"),
               names_to = "date",
               values_to = "value")
  
  # Convert date format
  new_df <- new_df %>% mutate(date = as.Date(date, format = "%m/%d/%y"))
  
  return(new_df)
}

counties_daily_cases <- reorganize_data(county_cases_df, cumulative=FALSE, population_adjusted=FALSE)
counties_cumu_cases <- reorganize_data(county_cases_df, cumulative=TRUE, population_adjusted=FALSE)
counties_cumu_perc_cases <- reorganize_data(county_cases_df, cumulative=TRUE, population_adjusted=TRUE)
counties_daily_perc_cases <- reorganize_data(county_cases_df, cumulative=FALSE, population_adjusted=TRUE)
```

# Create figures
## Create the county comparison time series figures
```{r Create time series figure}
create_policy_timeseries <- function(data, FIPS_codes, policies, y_axis_name, plot_title) {
  # Select the relevant counts
  interested <<- data %>% 
    filter(FIPS %in% FIPS_codes) %>%
    select(FIPS, county, state_code, date, value)
  
  # Find the policies for each region
  county_policies <<- policy_df %>%
    mutate(date = as.Date(date), fips_code = as.double(fips_code)) %>%
    filter(fips_code %in% FIPS_codes & policy_type %in% policies) %>%
    rename(FIPS = fips_code)
  
  # Merge the counts and policies
  combined_counts_policy <<- left_join(interested, county_policies, by=c("FIPS", "date")) %>%
    select(-c(state_id, policy_level, comments, source, county.y, total_phases)) %>%
    rename(county = county.x) %>%
    mutate(full_name=paste(county, ", ", state_code, sep=""))
  
  # Create the starting and stopping points of policies
  policy_implemented <<- combined_counts_policy %>% filter(start_stop == "start")
  policy_canceled <<- combined_counts_policy %>% filter(start_stop == "stop")

  # Create the plot
  combined_counts_policy %>%
    ggplot(aes(date, value, color=factor(full_name))) +
    theme_minimal() +
    geom_line() +
    geom_point(data=policy_implemented,
               aes(date,
                   value,
                   shape=factor(policy_type),
                   fill=factor(full_name)),
               alpha=0.5,
               size=5,
               stroke=0) +
    geom_point(data=policy_canceled,
               aes(date,
                   value,
                   shape=factor(policy_type)),
               alpha=0.5,
               fill=NA,
               size=4,
               stroke=2) +
    scale_fill_discrete(na.value=NA, guide="none") +
    scale_shape_manual(values=c(21,24,22,23,25)) +
    labs(color="Region",
         shape="Policy Type") +
    scale_x_date(date_labels = "%b",
                 date_breaks = "1 month") +
    xlab("Date") +
    ylab(y_axis_name) +
    ggtitle(plot_title)
}

create_policy_timeseries(counties_daily_cases, 
                         c(19013,08031,25025), 
                         c("Mask Requirement", 
                           "Shelter in Place", 
                           "Non-Essential Businesses", 
                           "Food and Drink", 
                           "Entertainment"),
                         "Number of cases",
                         "Daily new COVID-19 cases across regions")

create_policy_timeseries(counties_cumu_cases,
                         c(19013,08031,25025),
                         c("Mask Requirement", 
                           "Shelter in Place", 
                           "Non-Essential Businesses", 
                           "Food and Drink", 
                           "Entertainment"),
                         "Number of cases",
                         "Cumulative COVID-19 cases across regions")

create_policy_timeseries(counties_cumu_perc_cases,
                         c(19013,08031,25025),
                         c("Mask Requirement", 
                           "Shelter in Place", 
                           "Non-Essential Businesses", 
                           "Food and Drink", 
                           "Entertainment"),
                         "Fraction of population",
                         "Cumulative COVID-19 cases adjusted for population")

create_policy_timeseries(counties_daily_perc_cases,
                         c(19013,08031,25025),
                         c("Mask Requirement", 
                           "Shelter in Place", 
                           "Non-Essential Businesses", 
                           "Food and Drink", 
                           "Entertainment"),
                         "Fraction of population",
                         "Daily new COVID-19 cases adjusted for population")

```

## Create the mask-usage per state figure
```{r Create state mask usage dataframe}
mask_use_state_df <- county_deaths_df %>% 
  select(FIPS:Population) %>%
  inner_join(y=mask_use_df, by=c("FIPS" = "COUNTYFP"))

state_pop <- aggregate(mask_use_state_df$Population, 
                       by = list(mask_use_state_df$Province_State), 
                       FUN="sum") %>%
  rename(state=Group.1, population=x)

mask_use_state_df <- mask_use_state_df %>% left_join(y=state_pop, by=c("Province_State"="state")) %>%
  rename(State_population=population) %>%
  mutate(county_perc=Population/State_population) %>%
  mutate(NEVER_adj=NEVER*county_perc) %>%
  mutate(RARELY_adj=RARELY*county_perc) %>%
  mutate(SOMETIMES_adj=SOMETIMES*county_perc) %>%
  mutate(FREQUENTLY_adj=FREQUENTLY*county_perc) %>%
  mutate(ALWAYS_adj=ALWAYS*county_perc) %>%
  select(Province_State, NEVER_adj:ALWAYS_adj) %>%
  group_by(Province_State) %>%
  summarise_each(funs(sum)) %>%
  mutate(FREQ_ALWAYS_adj=FREQUENTLY_adj+ALWAYS_adj)
```

```{r}
states <- map_data("state")
mask_use_state_df$Province_State <- tolower(mask_use_state_df$Province_State)
choro_state <- merge(states, mask_use_state_df, by.x="region", by.y="Province_State")

ggplot(choro_state, aes(long, lat, group=group)) +
  geom_polygon(aes(fill=FREQ_ALWAYS_adj*100), color="white") +
  scale_fill_viridis(limits=c(0,100),
                     option = "D") +
  labs(fill="Percent of\npopulation") +
  ggtitle("Percentage of survey participants who responded that they 'always' or 'frequently' wear a facemask\n in public when social distancing is not possible (July 2020)") +
  theme_void() +
    theme(plot.title = element_text(hjust = 0.5,
                                    size=22),
          legend.title = element_text(size=18),
          legend.text = element_text(size=18),
          legend.position = c(0.9,0.4)) +
  coord_map(projection="mercator") +
  ggsave(filename=paste("figures/mask_usage_state.png", sep=""),
     device=png,
     dpi=300,
     limitsize = FALSE,
     height=1000,
     width=1000)
```

## Create the mask-usage per county figure
```{r}
mask_use_county_df <- mask_use_df %>% mutate(ALWAYS_FREQ = ALWAYS+FREQUENTLY) %>%
  left_join(y=county_deaths_df, by=c("COUNTYFP" = "FIPS")) %>%
  select(COUNTYFP, Admin2, Province_State, NEVER:ALWAYS_FREQ) %>%
  rename(county = Admin2, 
         state = Province_State)

mask_use_county_df$county <- tolower(mask_use_county_df$county)
mask_use_county_df$state <- tolower(mask_use_county_df$state)

choro_county <- left_join(map_data("county"), mask_use_county_df, 
                          by=c("subregion" = "county",
                               "region" = "state"))
```

```{r}
ggplot(choro_county, aes(long, lat, group=group)) +
  geom_polygon(aes(fill=ALWAYS_FREQ*100)) +
  scale_fill_viridis(limits=c(0,100),
                     option = "D") +
  labs(fill="Percent of\npopulation") +
  ggtitle("Percentage of survey participants who responded that they 'always' or 'frequently' wear a facemask\n in public when social distancing is not possible (July 2020)") +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5,
                                    size=22),
          legend.title = element_text(size=18),
          legend.text = element_text(size=18),
          legend.position = c(0.9,0.4)) +
  coord_map(projection="mercator") +
  ggsave(filename=paste("figures/mask_usage_county.png", sep=""),
     device=png,
     dpi=300,
     limitsize = FALSE,
     height=1000,
     width=1000)
```

## Create the cumulative case counts figures for counties 
```{r}
cumu_cases_county <- counties_cumu_cases
cumu_cases_county <- cumu_cases_county %>% 
  mutate(county = str_replace(county,  " County", "")) %>%
  mutate(county = str_replace(county,  " Parish", "")) %>%
  mutate(state_code = abbr2state(state_code)) %>%
  rename(state=state_code)

cumu_cases_county$county <- tolower(cumu_cases_county$county)
cumu_cases_county$state <- tolower(cumu_cases_county$state)
cumu_cases_county <- na.omit(cumu_cases_county)
```

```{r}
start_date <- as.Date("2020-01-22")
end_date <- as.Date("2020-11-16")

while (start_date < end_date) {
  filtered_df <- cumu_cases_county %>% filter(date == start_date)
  choro_cumu_county <- left_join(map_data("county"), 
                                  filtered_df,
                                  by=c("subregion" = "county",
                                       "region" = "state"))
  
  ggplot(choro_cumu_county, aes(long, lat, group=group)) +
    geom_polygon(aes(fill=value), color="black") +
    scale_fill_gradient2(low="white", high="red",
                         limits=c(0, 350000)) +
    labs(fill="Cases") +
    ggtitle(paste("Cumulative COVID-19 cases through:", start_date)) +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5,
                                    size=30),
          legend.title = element_text(size=22),
          legend.text = element_text(size=18),
          legend.position = c(0.9,0.4)) +
    coord_map(projection="mercator") +
    ggsave(filename=paste("figures/cumu_cases/cumu_cases_", start_date, ".png", sep=""),
         device=png,
         dpi=300,
         limitsize = FALSE,
         height=1000,
         width=1000)
  
  start_date <- start_date + 7
}
```

## Create the cumulative case counts figures for counties as a percentage of population
```{r}
cumu_perc_cases_county <- counties_cumu_perc_cases
cumu_perc_cases_county <- cumu_perc_cases_county %>% 
  mutate(county = str_replace(county,  " County", "")) %>%
  mutate(county = str_replace(county,  " Parish", "")) %>%
  mutate(state_code = abbr2state(state_code)) %>%
  rename(state=state_code)

cumu_perc_cases_county$county <- tolower(cumu_perc_cases_county$county)
cumu_perc_cases_county$state <- tolower(cumu_perc_cases_county$state)
cumu_perc_cases_county <- na.omit(cumu_perc_cases_county)
```

```{r}
start_date <- as.Date("2020-01-22")
end_date <- as.Date("2020-11-16")

while (start_date < end_date) {
  filtered_df <- cumu_perc_cases_county %>% filter(date == start_date)
  choro_cumu_county <- left_join(map_data("county"), 
                                  filtered_df,
                                  by=c("subregion" = "county",
                                       "region" = "state"))
  
  ggplot(choro_cumu_county, aes(long, lat, group=group)) +
    geom_polygon(aes(fill=value*100), color="black") +
    scale_fill_gradient2(low="white", high="red",
                         limits=c(0, 20)) +
    labs(fill="Percent of\npopulation") +
    ggtitle(paste("Percentage of population infected with COVID-19:", start_date)) +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5,
                                    size=30),
          legend.title = element_text(size=18),
          legend.text = element_text(size=18),
          legend.position = c(0.9,0.4)) +
    coord_map(projection="mercator") +
    ggsave(filename=paste("figures/cumu_perc/cumu_perc_",start_date,".png", sep=""),
         device=png,
         dpi=300,
         limitsize = FALSE,
         height=1000,
         width=1000)
  
  start_date <- start_date + 7
}
```


## Create the policy counts over time figures
```{r prepare policy df}
policy_counties <- policy_df %>%
  filter(policy_level == "county") %>%
  mutate(county = str_replace(county,  " County", "")) %>%
  mutate(county = str_replace(county,  " Parish", "")) %>%
  mutate(county = tolower(county)) %>%
  mutate(state = tolower(abbr2state(state_id))) %>%
  mutate(full_name = paste(county, ", ", state, sep="")) %>%
  mutate(start_stop = ifelse(start_stop == "start", 1, -1)) %>%
  select(full_name, county, state, date, start_stop)
  
policy_states <- policy_df %>%
  filter(policy_level == "state") %>%
  mutate(state_id = tolower(abbr2state(state_id))) %>%
  mutate(start_stop = ifelse(start_stop == "start", 1, -1)) %>%
  filter(!is.na(state_id)) %>%
  select(state_id, date, start_stop) %>%
  filter(date >= "2020-02-29")
```

```{r}
start_date <- as.Date("2020-01-22")
end_date <- as.Date("2020-11-15")

while (start_date < end_date) {
  county_totals <- policy_counties %>%
    filter(date <= start_date) %>%
    group_by(county, state) %>%
    summarise(running_total = sum(start_stop))
  
  state_totals <- policy_states %>%
    filter(date <= start_date) %>%
    group_by(state_id) %>%
    summarise(running_total = sum(start_stop))
  
  combined_totals <- left_join(map_data("county"),
                                  county_totals,
                                  by=c("subregion" = "county",
                                       "region" = "state")) %>%
    left_join(state_totals, by=c("region" = "state_id")) %>%
    mutate(running_total.x = ifelse(is.na(running_total.x), 0, running_total.x)) %>%
    mutate(total_policies = running_total.x + running_total.y)

  ggplot(combined_totals, aes(long, lat, group=group)) +
    geom_polygon(aes(fill=total_policies), color="black") +
    scale_fill_viridis(option="D",
                       limits=c(0,45)) + 
    labs(fill="Policies") +
    ggtitle(paste("Number of currently implemented state and county policies:", start_date)) +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5,
                                    size=30),
          legend.title = element_text(size=18),
          legend.text = element_text(size=18),
          legend.position = c(0.9,0.4)) +
    coord_map(projection="mercator") +
    ggsave(filename=paste("figures/policy_count/policy_count_",start_date,".png", sep=""),
         device=png,
         dpi=300,
         limitsize = FALSE,
         height=1000,
         width=1000)
  
  start_date <- start_date + 7
}
```